In [2]:
import pandas as pd

In [3]:
message = pd.read_csv("SMSSpamCollection.txt",sep='\t',names =['label','message'])
message

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
message.shape

(5572, 2)

In [5]:
message['message'].loc[100]

"Please don't text me anymore. I have nothing else to say."

In [6]:
import nltk

In [7]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
ps = PorterStemmer()

In [8]:
import re 

In [9]:
corpus =[]
for i in range(0,len(message)):
    review=re.sub('^a-zA-Z','',message['message'][i])
    review=review.lower()
    review=review.split()
    review = [ps.stem(word) for word in review if word not in set(stopwords.words('english'))]
    review =''.join(review)
    corpus.append(review)

In [10]:
corpus

['gojurongpoint,crazy..availbugingreatworldlaebuffet...cinegotamorwat...',
 'oklar...jokewifuoni...',
 "freeentri2wklicompwinfacupfinaltkt21stmay2005.textfa87121receiventriquestion(stdtxtrate)t&c'appli08452810075over18'",
 'udunsayearlihor...ucalreadisay...',
 'nahthinkgoeusf,livearoundthough',
 "freemsgheydarl3week'wordback!i'dlikefunstill?tbok!xxxstdchgsend,£1.50rcv",
 'evenbrotherlikespeakme.treatlikeaidpatent.',
 "perrequest'mellmell(oruminnaminungintnurunguvettam)'setcallertuncallers.press*9copifriendcallertun",
 'winner!!valunetworkcustomselectreceivea£900prizereward!claimcall09061701461.claimcodekl341.valid12houronly.',
 'mobil11monthmore?urentitlupdatlatestcolourmobilcamerafree!callmobilupdatcofree08002986030',
 "i'mgonnahomesoonwanttalkstuffanymortonight,k?i'vcrienoughtoday.",
 'sixchancwincash!10020,000poundtxt>csh11send87575.cost150p/day,6days,16+tsandcapplireplihl4info',
 'urgent!1weekfreemembership£100,000prizejackpot!txtword:claimno:81010t&cwww.dbuk.netlccltdpobox4403ldnw

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500,binary =True,ngram_range=(2, 2))

In [12]:
 x=cv.fit_transform(corpus).toarray()


In [13]:
x.shape

(5572, 2500)

In [14]:
x[1]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [15]:
y = pd.get_dummies(message['label'])
y =y.iloc[:,1].values

In [16]:
y = y.reshape(-1)

In [17]:
y

array([False, False,  True, ..., False, False, False])

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.2,random_state =0)

In [20]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [22]:
y_train

array([False, False, False, ...,  True, False, False])

In [23]:
y_test

array([False,  True, False, ..., False,  True, False])

In [24]:
from sklearn.naive_bayes import MultinomialNB
spam_detection_model = MultinomialNB()


In [25]:
spam_detection_model.fit(x_train, y_train)

MultinomialNB()

In [26]:
y_pred =spam_detection_model.predict(x_test)

In [27]:
y_pred

array([False, False, False, ..., False,  True, False])

In [28]:
from sklearn.metrics import accuracy_score,classification_report

In [29]:
accurancy_score = accuracy_score(y_test,y_pred)

In [30]:
accurancy_score

0.9300448430493273

In [31]:
CR = classification_report(y_test,y_pred)

In [32]:
print(CR)

              precision    recall  f1-score   support

       False       0.92      1.00      0.96       955
        True       1.00      0.51      0.68       160

    accuracy                           0.93      1115
   macro avg       0.96      0.76      0.82      1115
weighted avg       0.94      0.93      0.92      1115



In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500,ngram_range=(1, 2))

In [34]:
x = tv.fit_transform(corpus).toarray()

In [35]:
x[1]

array([0., 0., 0., ..., 0., 0., 0.])

In [36]:
y = pd.get_dummies(message['label'])
y =y.iloc[:,1].values

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.1,random_state =0)

In [39]:
from sklearn.naive_bayes import MultinomialNB
spam_detection_model = MultinomialNB()


In [40]:
spam_detection_model.fit(x_train, y_train)

MultinomialNB()

In [41]:
y_pred =spam_detection_model.predict(x_test)

In [42]:
accurancy_score = accuracy_score(y_pred,y_test)

In [43]:
accurancy_score

0.9336917562724014

In [44]:
CR = classification_report(y_pred,y_test)

In [45]:
print(CR)

              precision    recall  f1-score   support

       False       1.00      0.93      0.96       518
        True       0.52      1.00      0.68        40

    accuracy                           0.93       558
   macro avg       0.76      0.96      0.82       558
weighted avg       0.97      0.93      0.94       558



In [46]:
from sklearn.ensemble import RandomForestClassifier


In [47]:
Classifier =RandomForestClassifier()
Classifier.fit(x_train,y_train)

RandomForestClassifier()

In [48]:
y_pred= Classifier.predict(x_test)

In [49]:
from sklearn.metrics import accuracy_score,classification_report

In [50]:
accurancy_score

0.9336917562724014

In [51]:
CR = classification_report(y_test,y_pred)

In [52]:
print(CR)

              precision    recall  f1-score   support

       False       0.95      1.00      0.97       481
        True       1.00      0.68      0.81        77

    accuracy                           0.96       558
   macro avg       0.98      0.84      0.89       558
weighted avg       0.96      0.96      0.95       558



In [53]:
!pip install gensim




[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [54]:
import gensim


In [55]:
import gensim.downloader as api

In [56]:
wv = api.load('word2vec-google-news-300')

[--------------------------------------------------] 1.4% 23.4/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[=-------------------------------------------------] 4.0% 65.8/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[===-----------------------------------------------] 6.7% 111.4/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[====----------------------------------------------] 9.4% 156.6/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[=====---------------------------------------------] 11.8% 197.0/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[===============-----------------------------------] 30.3% 504.5/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[==================--------------------------------] 37.6% 625.1/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[===================-------------------------------] 40.0% 664.8/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[=====================-----------------------------] 42.2% 702.5/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[======================----------------------------] 44.4% 738.4/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[=======================---------------------------] 46.7% 776.9/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[========================--------------------------] 49.3% 819.5/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[=========================-------------------------] 51.6% 858.6/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[==========================------------------------] 53.9% 896.7/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[============================----------------------] 56.9% 945.7/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[=============================---------------------] 59.9% 996.1/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[===============================-------------------] 62.9% 1045.3/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[================================------------------] 65.3% 1085.9/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[=================================-----------------] 67.7% 1126.4/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[======================================------------] 76.2% 1267.8/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[=======================================-----------] 78.3% 1301.2/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[========================================----------] 80.2% 1333.6/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[=========================================---------] 82.4% 1370.3/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[==========================================--------] 84.2% 1400.4/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[===========================================-------] 86.1% 1432.0/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[============================================------] 88.3% 1467.9/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[=============================================-----] 90.5% 1504.7/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[==============================================----] 92.7% 1541.0/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[===============================================---] 94.8% 1577.1/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[================================================--] 97.2% 1616.9/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[=================================================-] 99.7% 1657.8/1662.8MB downloaded

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [57]:
from nltk.stem import WordNetLemmatizer

In [58]:
WN =WordNetLemmatizer()

In [59]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

In [60]:
corpus =[]
for i in range(0,len(message)):
    review=re.sub('^a-zA-Z','',message['message'][i])
    review=review.lower()
    review=review.split()
    review = [WN.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review =''.join(review)
    corpus.append(review)

In [61]:
corpus

['gojurongpoint,crazy..availablebugisngreatworldlaebuffet...cinegotamorewat...',
 'oklar...jokingwifuoni...',
 "freeentry2wklycompwinfacupfinaltkts21stmay2005.textfa87121receiveentryquestion(stdtxtrate)t&c'sapply08452810075over18's",
 'udunsayearlyhor...ucalreadysay...',
 'nahthinkgousf,lifearoundthough',
 "freemsgheydarling3week'swordback!i'dlikefunstill?tbok!xxxstdchgssend,£1.50rcv",
 'evenbrotherlikespeakme.treatlikeaidpatent.',
 "perrequest'mellemelle(oruminnaminungintenurunguvettam)'setcallertunecallers.press*9copyfriendcallertune",
 'winner!!valuednetworkcustomerselectedreceivea£900prizereward!claimcall09061701461.claimcodekl341.valid12houronly.',
 'mobile11monthmore?urentitledupdatelatestcolourmobilecamerafree!callmobileupdatecofree08002986030',
 "i'mgonnahomesoonwanttalkstuffanymoretonight,k?i'vecriedenoughtoday.",
 'sixchancewincash!10020,000poundtxt>csh11send87575.cost150p/day,6days,16+tsandcsapplyreplyhl4info',
 'urgent!1weekfreemembership£100,000prizejackpot!txtword:claimno

In [62]:
simple_preprocess

<function gensim.utils.simple_preprocess(doc, deacc=False, min_len=2, max_len=15)>

In [63]:
words =[]
for sent in corpus:
    sent_tokens= sent_tokenize(sent)
    for sent in sent_tokens:
        words.append(simple_preprocess(sent))

In [64]:
words

[['gojurongpoint', 'crazy', 'cinegotamorewat'],
 ['oklar', 'jokingwifuoni'],
 ['freeentry', 'stmay', 'textfa', 'stdtxtrate', 'sapply', 'over'],
 ['udunsayearlyhor', 'ucalreadysay'],
 ['nahthinkgousf'],
 ['week', 'swordback', 'dlikefunstill', 'tbok', 'xxxstdchgssend', 'rcv'],
 [],
 ['perrequest', 'mellemelle', 'press'],
 ['winner'],
 ['prizereward', 'claimcall', 'claimcodekl', 'valid', 'houronly'],
 ['mobile', 'monthmore'],
 [],
 ['poundtxt', 'csh', 'send', 'cost', 'day', 'days', 'info'],
 ['urgent',
  'prizejackpot',
  'txtword',
  'claimno',
  'cwww',
  'dbuk',
  'netlccltdpobox',
  'ldnw',
  'rw'],
 [],
 ['datesundaywill'],
 [],
 ['usecredit', 'http', 'wap', 'com', 'qjkgighjjgcbl'],
 ['ohk', 'mwatchinghere'],
 ['ehuremember', 'spellname', 'yesdid'],
 ['finethat', 'swayufeel', 'that', 'swaygotab'],
 ['dontmissgoals',
  'teamnews',
  'egengland',
  'try',
  'wales',
  'scotland',
  'txt',
  'poboxox',
  'wq'],
 [],
 ['mgoingtry', 'monthhahajoking'],
 ['üpayfirstlar', 'dastockcomin'],
 

#### Word2Vector

In [65]:
import gensim

In [66]:
model = gensim.models.Word2Vec(words,window =5,min_count=2)
model

In [67]:
model.wv.index_to_key

['gt',
 'lt',
 'call',
 'amp',
 'ok',
 'sorry',
 'now',
 'urgent',
 'co',
 'no',
 'that',
 'love',
 'can',
 'com',
 'pobox',
 'ppm',
 'www',
 'we',
 'yes',
 'min',
 'uk',
 'hi',
 'llcalllater',
 'free',
 'you',
 'day',
 'landline',
 'haha',
 'pm',
 'how',
 'pleasecall',
 'cash',
 'mobile',
 'claim',
 'hrs',
 'lol',
 'hello',
 'valid',
 'win',
 'goodmorning',
 'hey',
 'decimal',
 'prize',
 'msg',
 'takecare',
 'know',
 'yeah',
 'prizeguaranteed',
 'xx',
 'oh',
 'thanx',
 'great',
 'optout',
 'txt',
 'what',
 'there',
 'need',
 'babe',
 'thanks',
 'tone',
 'callmobileupd',
 'am',
 'cost',
 'age',
 'goodnight',
 'get',
 'sms',
 'gudni',
 'award',
 'want',
 'expires',
 'identifiercode',
 'private',
 'freeentry',
 'it',
 'suite',
 'sir',
 'go',
 'gr',
 'uwan',
 'aight',
 'help',
 'stop',
 'wait',
 'mths',
 'cool',
 'yup',
 'congrats',
 'good',
 'hmmm',
 'freemsg',
 'sk',
 'info',
 'well',
 'oklor',
 'nite',
 'today',
 'box',
 'princess',
 'plssendmessage',
 'points',
 'bt',
 'only',
 'dear'

In [68]:
model.corpus_count

5780

In [69]:
model.epochs

5

In [70]:
model.wv.similar_by_word('prize')

[('xh', 0.35917186737060547),
 ('itcouldu', 0.3322986662387848),
 ('stillawake', 0.3007659316062927),
 ('lettry', 0.2978523075580597),
 ('mok', 0.28672316670417786),
 ('claimweekoffer', 0.28071537613868713),
 ('now', 0.2801194489002228),
 ('lovepetexx', 0.27590134739875793),
 ('samxxx', 0.2726421356201172),
 ('asked', 0.2722940146923065)]

In [71]:
model.wv.similar_by_word('happy')

[('hornyguyurarea', 0.3288816809654236),
 ('pound', 0.30292266607284546),
 ('hee', 0.27991992235183716),
 ('probablynot', 0.2796308398246765),
 ('ah', 0.2710137367248535),
 ('vubcm', 0.26877933740615845),
 ('llbgoing', 0.26601362228393555),
 ('btfixedlinecost', 0.26413992047309875),
 ('row', 0.26341116428375244),
 ('urbrilliant', 0.26093026995658875)]

In [72]:
model.wv.similar_by_word('bad')

[('congratulation', 0.3176775276660919),
 ('nice', 0.2886621654033661),
 ('godsaid', 0.284656822681427),
 ('santhony', 0.2798507809638977),
 ('co', 0.268606960773468),
 ('bewarefrauds', 0.261199027299881),
 ('freeentry', 0.255942702293396),
 ('keeptenrshelf', 0.2558407187461853),
 ('layrock', 0.24995028972625732),
 ('gbipodmp', 0.24687185883522034)]

In [86]:
import numpy as np


In [87]:
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0 )

In [88]:
type(model.wv.index_to_key)

list

In [89]:
words

[['gojurongpoint', 'crazy', 'cinegotamorewat'],
 ['oklar', 'jokingwifuoni'],
 ['freeentry', 'stmay', 'textfa', 'stdtxtrate', 'sapply', 'over'],
 ['udunsayearlyhor', 'ucalreadysay'],
 ['nahthinkgousf'],
 ['week', 'swordback', 'dlikefunstill', 'tbok', 'xxxstdchgssend', 'rcv'],
 [],
 ['perrequest', 'mellemelle', 'press'],
 ['winner'],
 ['prizereward', 'claimcall', 'claimcodekl', 'valid', 'houronly'],
 ['mobile', 'monthmore'],
 [],
 ['poundtxt', 'csh', 'send', 'cost', 'day', 'days', 'info'],
 ['urgent',
  'prizejackpot',
  'txtword',
  'claimno',
  'cwww',
  'dbuk',
  'netlccltdpobox',
  'ldnw',
  'rw'],
 [],
 ['datesundaywill'],
 [],
 ['usecredit', 'http', 'wap', 'com', 'qjkgighjjgcbl'],
 ['ohk', 'mwatchinghere'],
 ['ehuremember', 'spellname', 'yesdid'],
 ['finethat', 'swayufeel', 'that', 'swaygotab'],
 ['dontmissgoals',
  'teamnews',
  'egengland',
  'try',
  'wales',
  'scotland',
  'txt',
  'poboxox',
  'wq'],
 [],
 ['mgoingtry', 'monthhahajoking'],
 ['üpayfirstlar', 'dastockcomin'],
 

In [78]:
! pip install tqdm


[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [90]:
from tqdm import tqdm

In [94]:
X =[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

100%|███████████████████████████████████████████████████████████████████████████| 5780/5780 [00:00<00:00, 23019.02it/s]


In [99]:
X

[array([-0.00312316,  0.00091944, -0.00837904, -0.00569925, -0.00534647,
        -0.00321477,  0.00058228, -0.00456988, -0.00349126, -0.00753211,
         0.00329251,  0.00766387,  0.00110038,  0.00124391, -0.00993622,
         0.00290086,  0.00786588, -0.0038886 , -0.00757332,  0.00201423,
        -0.00900826,  0.00574738, -0.00526524,  0.00732176, -0.00313737,
        -0.00747755,  0.00403191,  0.00837107, -0.0065163 , -0.00692838,
        -0.00671914, -0.00341867,  0.00911861, -0.00353852,  0.00680796,
         0.00354209, -0.00697529, -0.00437594, -0.00647048, -0.00119339,
         0.00725763,  0.0020479 , -0.00313427,  0.00128253, -0.00491395,
         0.00450516, -0.00762087,  0.0048685 , -0.00492557, -0.00691092,
        -0.00256407,  0.00058678, -0.00304851, -0.00125495, -0.00327382,
         0.00760021, -0.00331987, -0.00448225, -0.00803243, -0.00587667,
        -0.00465477,  0.0011251 ,  0.00268263,  0.00704657,  0.00171004,
         0.00878463,  0.00884963,  0.00867125,  0.0

In [98]:
X_new = np.array(X)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5780,) + inhomogeneous part.

In [97]:
X_new

NameError: name 'X_new' is not defined